apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: srnn5ax77-go 
  janus-idp.io/tekton: srnn5ax77-go
  backstage.io/kubernetes-id: srnn5ax77-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: srnn5ax77-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml