apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: srnn5ax77-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srnn5ax77-go 
  name: srnn5ax77-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: srnn5ax77-go 
